nama = [
	'Dymar Mahafa',
	'Dita Dyah Saraswati',
	'Isnaini Annisa',
	'Rina Lailana',
	'Riovani Dian Putri',
	'Shinta Dewi Wijiarti',
	'Alif Kiky Listiyati',
	'Anis Khoiriyah',
	'Atikah Bakir',
	'Herdiawan Dwi Septiyana',
	'Heru Widayanto',
	'Dunyati Ilmiah',
	'Juni Dwi Riyanti',
	'Sri Lestari / El-Lisa',
	'Lutfi Yulianto',
	'Muhammad',
	'Raisha Nafisa',
	'M.Saepudin',
	'Sakifah',
	'Mungky Hendriyani',
	'Walimin',
	'Widhyanua Sarjana Aryandari',
	'Estina',
	'Wakhid Syamsudin',
	'Agus Heri Widodo',
	'Ilham Ramanto',
	'Ana Zuhriatun Nisa',
	'Novia Anggraini',
	'Vinny Martina',
	'Sovia',
	'NA Fadli',
	'Sri Wahyuni',
	'Wiwid NW',
	'Suparto',
	'Winda',
	'Mabruroh',
	'Nur Musabikah',
	'Hiday Nur',
	'Nova DW',
	'MS WIjaya',
	'Sabrina AL'
]

genre = [
	'Fiksi',
	'NonFiksi'
]